//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int id { get; set; }
        public string nombre_completo { get; set; }
        public string nombre_usuario { get; set; }
        public string pass { get; set; }
        public int idNivel { get; set; }
        public int idEstatus { get; set; }
    
        public virtual cEmpleadoEstatus cEmpleadoEstatus { get; set; }
        public virtual cEmpleadoNivel cEmpleadoNivel { get; set; }
    }
}
