//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entradas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entradas()
        {
            this.Detalle_Entradas = new HashSet<Detalle_Entradas>();
        }
    
        public int id { get; set; }
        public int idEmpleado { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public decimal importe { get; set; }
        public int idProveedor { get; set; }
        public int idEstatus { get; set; }
    
        public virtual cEntradaEstatus cEntradaEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Entradas> Detalle_Entradas { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
